---
- name: start kafka, jhipster registry
  hosts: all
  become: true
  tasks:
    - name: start docker service
      shell: docker-compose up -d {{ item }} chdir={{ docker_folder }}
      with_items:
        - "jhipster-registry"
        - "zookeeper"
        - "kafka"
